title: Gpu Offloading Manager
name: gom-app
adopt-info: gom-app
license: GPL-3.0+
version: '0.1.0'
summary: A simple GTK4 application for managing gpu offloading on linux
description: |
  GPU Offloading Manager aims to implement an user interface to configure and launch programs automatically under systems with hybrid graphics.
  _Note: the application is still under development, and as such, missing functionality, bugs and crashes are to be expected._

base: core22
grade: devel
confinement: strict
architectures:
   - build-on: amd64
compression: lzo
source-code: https://github.com/plasmus777/gom-app/
issues: https://github.com/plasmus777/gom-app/issues

plugs:
   $HOME/.config/gom-app:
      interface: personal-files
      read: $HOME/.config/gom-app
      write: $HOME/.config/gom-app
   $HOME/.local/share/applications:
      interface: personal-files
      read: $HOME/.local/share/applications
      write: $HOME/.local/share/applications
   /usr/share/applications:
      interface: system-files
      read: /usr/share/applications

apps:
  gom-app:
    extensions: [gnome]
    command: gom-app
    desktop: /usr/share/applications/plasmus777.gnome.GpuOffloadingManager.desktop
    common-id: plasmus777.gnome.GpuOffloadingManager.desktop
    plugs:
       - desktop
       - desktop-launch
       - network
       - polkit
       - system-observe
       - $HOME/.config/gom-app
       - $HOME/.local/share/applications
       - /usr/share/applications


parts:
  gom-app:
    source: https://github.com/plasmus777/gom-app
    source-tag: '43'
    source-type: git
    plugin: [meson, python]
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    parse-info: [usr/share/metainfo/plasmus777.gnome.GpuOffloadingManager.appdata.xml]

slots:
  gom-app:
    interface: dbus
    bus: session
    name: plasmus777.gnome.GpuOffloadingManager