title: Gpu Offloading Manager
name: gom-app
adopt-info: gom-app
version: '0.1.0'
summary: A simple GTK4 application for managing gpu offloading on linux
description: |
  GPU Offloading Manager aims to implement an user interface to configure and launch programs automatically under systems with hybrid graphics.
  _Note: the application is still under development, and as such, missing functionality, bugs and crashes are to be expected._
source-code: https://github.com/plasmus777/gom-app/
website: https://github.com/plasmus777
issues: https://github.com/plasmus777/gom-app/issues
license: GPL-3.0+

base: core22
grade: devel
confinement: strict
architectures:
   - amd64
compression: lzo

plugs:
   gom-app-config:
   user-applications-override:
      interface: personal-files
      read: |
         - $HOME/.local/share/applications
      write: |
         - $HOME/.local/share/applications
   system-applications:
      interface: system-files
      read: |
         - /usr/share/applications

apps:
  gom-app:
    extensions: [gnome]
    command: /usr/bin/gom-app
    desktop: usr/share/applications/com.github.plasmus777.GpuOffloadingManager.desktop
    common-id: gom-app
    plugs:
       - desktop
       - desktop-legacy
       - wayland
       - x11
       - gsettings
       - network
       - personal-files
       - system-files
       - system-observe
       - user-applications-override
       - system-applications

parts:
  gom-app:
    source: https://github.com/plasmus777/gom-app.git
    source-type: git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    parse-info: [usr/share/appdata/com.github.plasmus777.GpuOffloadingManager.appdata.xml]

slots:
  gom-app:
    interface: dbus
    bus: session
    name: com.github.plasmus777.GpuOffloadingManager